// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsjhU-4hbBChWkSMCbRfhF6J33G0y4Ps0',
    appId: '1:190252245379:web:e56671ef9136193c1996b6',
    messagingSenderId: '190252245379',
    projectId: 'flutter-login-app-5bce8',
    authDomain: 'flutter-login-app-5bce8.firebaseapp.com',
    databaseURL: 'https://flutter-login-app-5bce8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-login-app-5bce8.firebasestorage.app',
    measurementId: 'G-JG8L41V66M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRB0oMby1dipHVOiak92gszgOUN4I0Cqo',
    appId: '1:190252245379:android:50f53818ba68496f1996b6',
    messagingSenderId: '190252245379',
    projectId: 'flutter-login-app-5bce8',
    databaseURL: 'https://flutter-login-app-5bce8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-login-app-5bce8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6NO-_1CM8UJySh8Kpp4pV5-QpUJbQGxY',
    appId: '1:190252245379:ios:320921d9147fb41e1996b6',
    messagingSenderId: '190252245379',
    projectId: 'flutter-login-app-5bce8',
    databaseURL: 'https://flutter-login-app-5bce8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-login-app-5bce8.firebasestorage.app',
    iosBundleId: 'com.example.uas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6NO-_1CM8UJySh8Kpp4pV5-QpUJbQGxY',
    appId: '1:190252245379:ios:320921d9147fb41e1996b6',
    messagingSenderId: '190252245379',
    projectId: 'flutter-login-app-5bce8',
    databaseURL: 'https://flutter-login-app-5bce8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-login-app-5bce8.firebasestorage.app',
    iosBundleId: 'com.example.uas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsjhU-4hbBChWkSMCbRfhF6J33G0y4Ps0',
    appId: '1:190252245379:web:5ae6f62944fa4fe61996b6',
    messagingSenderId: '190252245379',
    projectId: 'flutter-login-app-5bce8',
    authDomain: 'flutter-login-app-5bce8.firebaseapp.com',
    databaseURL: 'https://flutter-login-app-5bce8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-login-app-5bce8.firebasestorage.app',
    measurementId: 'G-2JZ9H1K4RH',
  );
}
